### ISSUE TITLE
我这边编译一直通不过，网上也找了好多这个适配的代码

### ISSUE THREAD

**Issue by LB-ocean** [Vension/V-SmallestWidthDemo#1]
这是编译错误提示
Exception in thread "main" java.lang.ClassNotFoundException: me.vension.smallestwidth.demo.DimenGenerator
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at com.intellij.rt.execution.application.AppMainV2.main(AppMainV2.java:107)

大神，可否加一下你qq，细聊一下 关于 屏幕适配，向您学习； 我qq： 207563927；

**Comment by Vension** [comment]
是运行main函数哦，不是运行APP那样run
